README.md

By default, there is no shortcut to open "User Preferences"

Remove invalid shortcut

---

package.json
src/extension.ts
src/services/commandService.ts

Implement diagnostics for cargo output (warning and error highlighting), and add command Cargo Check.
Linting should probably be implemented by debouncing document edits and calling `cargo check`. The command service should also keep a reference to the command currently being executed, and terminate it before running any other commands, this implies that there should be a `force` argument, that user run commands is set to true, and internally run commands sets to false, like this, when the user runs a command in the middle of a lint, the lint will stop to run the user command, but if the lint runs while a user command is running, it will do nothing.

Add diagnostic handling to commandService

---

src/services/commandService.ts
src/services/suggestService.ts

Add missing executable messages for `cargo` and `racer`, using the same format as the message for `rustfmt`.
Fixes https://github.com/saviorisdead/RustyCode/issues/22.
This will probably need to be rebased if you merge #24, just send me a message and I will rebase so you can merge smoothly.

Standard messages for missing executables

---

package.json
src/extension.ts
src/services/commandService.ts
typings/tree-kill/tree-kill.d.ts

Note: the changed indentations on package.json were caused by `npm --save tree-kill`, when searching for the cause, I found https://github.com/npm/npm/issues/4718, npm has no plans to change it's behavior, so I suggest using this indentation to `npm`.
Side note: Would you be ok with a pull request adding a tslint.json, and normalizing the style through the repo? If so, should we use tabs or spaces?

Add terminate command, rename cargo commands to match task commands

---

src/services/commandService.ts

This pull request makes the promise returned form CargoTask.execute resolve into the output of the cargo task and CommandService.runCargo to run that output through parseDiagnostics.
This makes errors from failed cargo builds show up as diagnostics.
Fix for #50

Run parseDiagnostics on failed CargoTasks

---

src/services/suggestService.ts

This pull request add support for showing signature help for function calls that several lines.
The current (0.6.0) behaviour is for the signature help to disappear when you press enter:

Add support for multiline function call signature help

---

src/services/suggestService.ts

This pull request makes the suggest service check for the correct function name when showing the signature.
New behaviour (shows signature of `say` when calling `say`):
Old behaviour (shows signature of `say_hello` when calling `say`):

Check function name when showing signature

---

README.md
src/extension.ts

I've been using Atom before, there is a plugin 'rust-linter' that runs `cargo check` on save and highlights errors and warnings.
This PR adds simmilar option to RustyCode based on `rust.cargo.check`. It is as experimental as `formatOnSave`, since it uses the same code. The name of a new option is `checkOnSave`.
I've also added a pair of lines to README.md to folow this addition.

Added option to cargo check on save

---

README.md
package.json
src/extension.ts

[Clippy](https://github.com/Manishearth/rust-clippy) is a powerful linter for Rust with some really useful warnings. This PR allows RustyCode to lint code on save (if `checkOnSave` is enabled) through [`cargo-clippy`](https://github.com/White-Oak/cargo-clippy) subcommand (if `useClippyInsteadOfCheck` is enabled). `cargo-clippy` should be installed (via `cargo install`) to use it.

Add option to use clippy to lint project on save

---

.vscode/launch.json

The new release of VS Code (0.10.10) requires paths in launch.json to be absolute. This PR fixes that.

Fix launch.json relative paths

---

package.json

Currently when you try to build when Cargo.toml is chosen you cannot.

Build is allowed when Cargo.toml is chosen

---

src/services/suggestService.ts

**Supersedes #82 to free up my master branch**
Currently, there is a bug where the ctrl+hover functionality of RustyCode is broken after a racer daemon restart. This can be demonstrated by:
1. Open a Rust source file
2. Hold down ctrl and hover a few symbols; observe that valid symbols are underlined and their definitions pop up
3. Hover over a comment or a string and racer will crash
4. Close the error message, triggering a restart of RustyCode's suggestions provider
5. The ctrl+hover functionality is now broken
The breakage is due to a callback never getting called back after racer crashes. This makes VS Code wait forever for a response, blocking all future calls on ctrl+hover.
The fix is simply to invoke the all the pending callbacks before relaunching the racer daemon.

Fix breakage of ctrl+hover functionality on racer daemon restart

---

src/services/commandService.ts

`rustc` occasionally emits diagnostics prefixed with `note:` and `help:`. This is most prevalent with the borrow and region checkers, which will emit `note` diagnostics at the source of the borrow and the region that a borrow is valid, respectively.
Here's a code sample before this change:
And after:
With this change the first `x` is highlighted green, as `rustc` indicates it as immutable binding.
Region checker diagnostics tend to span the entire region whose lifetime a borrow escapes, like this:
This ends up with a swath of green highlighting. This isn't the best, I think, but other editors have this same problem (a side effect of the spans that `rustc` gives us). You can see also in this example a borrow checker diagnostic highlighting green the right bracket indicating the location …

add 'help' and 'note' modes to diagnostic detection

---

README.md
package.json
src/extension.ts

Inspiration taken from Atom's [linter-rust](https://github.com/AtomLinter/linter-rust/blob/master/lib/linter-rust.coffee#L113). The main problem of using `cargo check` is due to the this https://github.com/rsolomo/cargo-check/issues/4 .

Enable check with `cargo build`.

---

package.json
src/services/commandService.ts

Update vscode engine version to `1.0.0`, so we can use the new interface and fix #26 properly.
As tradition demands, apparently npm insists on changing every single line of the package.json when running `npm install`.

Update vscode and fix #26 properly

---

src/services/formatService.ts

This PR allows us to bypass a problem in `rustfmt` where it'll panic when the environment variable TERM isn't set (https://github.com/rust-lang-nursery/rustfmt/issues/978). If TERM isn't set, default to "xterm" as a best guess.
This might fix https://github.com/saviorisdead/RustyCode/issues/119, but it's hard to be sure since everyone has a different set up.

Set the TERM environment variable when calling rustfmt

---

src/services/formatService.ts

When using the extension to format code that contains a line that cannot be formatted (but is non-fatal), rustfmt will output a warning and continue formatting the rest of the file. Rustfmt sets the exit code to `3`, which the extension interprets as a fatal error and emits the 'Cannot format due to syntax errors' message.
I've added a check to exclude the error condition in the event that such a warning is encountered.

Fixed rustfmt error handling to continue when non-fatal errors are encountered

---

src/extension.ts

Fixes https://github.com/saviorisdead/RustyCode/issues/148
I don't write JavaScript/TypeScript, this felt like a trivial fix though. Tested and working, still formats rust code files, and it doesn't attempt to format .toml's.

Prevent the formatter from running on non-rust code files

---

src/extension.ts

Using `rustRegex.exec(document.fileName).length === 0` was erroring on every second save as the `/g` flag meant that it was starting from the end of the last match.
Changed it to `document.fileName.match(rustRegex).length`.

Fixed a bug in PR #149. The regex expression was failing on every second iteration

---

src/rustSymbols.ts

Adds support for [rustsym](https://github.com/trixnz/rustsym) 0.3.0 which enables searching for macros via Go To Symbol.

Add support for rustsym 0.3.0 which enables searching for macros

---

package.json
src/extension.ts
src/services/commandService.ts

The Cargo output is somewhat preserved by manually emitting Rust formatted errors, although it is not a complete solution. It does, however, provide a much better output than a giant JSON blob.
As per the discussion in #146, this uses `RUSTFLAGS` while the `error-format` feature is unstable. Hopefully `error-format` makes its way into Cargo so we can issue JSON builds from the IDE without `RUSTFLAGS` as this currently invalidates the internal fingerprint in `rustc`.
I've also refactored the error parsing to be a little more generic so future additions (like parsing the new Rust error format) can be added trivially.
***Edit:*** Went ahead and added support for the new error format (`RUST_NEW_ERROR_FORMAT=true`) that is set to become the new default in the future.

Add support for JSON error format and new (RUST_NEW_ERROR_FORMAT=true) error style

---

src/services/formatService.ts

Also changed the `Cannot format due to syntax errors` nag to show in the status bar which will disappear after 5 seconds, rather than a big popup as this becomes tedious after a while. Thoughts?
Exit code 4 reference PR: https://github.com/rust-lang-nursery/rustfmt/issues/906

Added support for exit code 4 when using diff mode in recent(master) versions of rustfmt

---

README.md
package.json
src/extension.ts

The main problem this tries to solve is that in a complex project which
consists of a library and binaries which use it it's much more important
to iterate on the library itself rather than on binaries and `check`
command is pretty important.
While solving this issue in a general case might be complicated (it
needs binary name), the solution for library case is quite simple - all
we need to do is to pass `--lib`.
This commit adds additional internal command `rust.cargo.check.lib` and
exposes it as:
1. "Cargo: Check Library" task
2. `cargo-lib` as a new option for `checkWith` workspace configuration
value
So the easiest way is to set `checkWith` to `cargo-lib`
Fixes #131

Added a separate check command for library

---

package.json
src/extension.ts
src/installTools.ts

This adds a button in the status bar to allow the user to download the various tools we use. This is limited to those that can be installed by `cargo` for simplicity.
The user will need to have `cargo` and `rust` installed for this to function. I think its a reasonable expectation for these prerequisites to be met, but am open to discussion.

Added a button for the user to install the required tools we depend on for extended functionality.

---

README.md
package.json
src/services/commandService.ts

rust.cargoEnv can be used to set custom environment variables when running
cargo. This is useful for compiling some crates like openssl-sys.
For example to compile openssl-sys on osx with openssl from homebrew, the
following can be set in settings.json:
"rust.cargoEnv": {
"OPENSSL_INCLUDE_DIR": "/usr/local/opt/openssl/include",
"OPENSSL_LIB_DIR": "/usr/local/opt/openssl/lib"
}

Add rust.cargoEnv configuration key

---

src/installTools.ts

Woops. Bug discovered by @boyedarat in #186.

Fixed issue where tool paths specified by the user were always being reported as not existing due to a bad use of Futures
